FROM node:18.13.0-alpine@sha256:fda98168118e5a8f4269efca4101ee51dd5c75c0fe56d8eb6fad80455c2f5827

ARG NODO_MOCK_COMMIT_SHA

RUN apk update && apk upgrade && \
    apk add --no-cache bash ca-certificates git openssh openssl

WORKDIR /usr/src/app

RUN rm -rf * && \
  git clone https://github.com/pagopa/io-pagopa-node-mock.git /usr/src/app && \
  git checkout ${NODO_MOCK_COMMIT_SHA}

RUN yarn install && \
    yarn build

EXPOSE ${PAGOPA_PORT}

CMD ["yarn", "start"]
