FROM node:22.13.1-slim@sha256:83fdfa2a4de32d7f8d79829ea259bd6a4821f8b2d123204ac467fbe3966450fc

ARG NOTIFICATIONS_SERVICE_COMMIT_SHA

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -y --no-install-recommends bash ca-certificates git openssh-client chromium

ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
    PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

WORKDIR /usr/src/app

RUN rm -rf * && \
  git clone https://github.com/pagopa/pagopa-notifications-service.git /usr/src/app && \
  git checkout ${NOTIFICATIONS_SERVICE_COMMIT_SHA}

RUN yarn install && \
    yarn build

CMD ["yarn", "start"]
