### 1. Cloning stage
FROM alpine/git:latest@sha256:d453f54c83320412aa89c391b076930bd8569bc1012285e8c68ce2d4435826a3 AS clone
WORKDIR /workspace/pagopa-ecommerce-event-dispatcher-service

ARG ECOMMERCE_EVENT_DISPATCHER_COMMIT_SHA

RUN rm -rf * && \
    git clone https://github.com/pagopa/pagopa-ecommerce-event-dispatcher-service.git /workspace/pagopa-ecommerce-event-dispatcher-service && \
    git checkout ${ECOMMERCE_EVENT_DISPATCHER_COMMIT_SHA} 

### 2. Build stage
FROM amazoncorretto:21-alpine@sha256:6a98c4402708fe8d16e946b4b5bac396379ec5104c1661e2a27b2b45cf9e2d16 AS build
WORKDIR /workspace/pagopa-ecommerce-event-dispatcher-service/

RUN apk add --no-cache git curl ca-certificates gettext

ARG REPO=/workspace/pagopa-ecommerce-event-dispatcher-service

COPY --from=clone ${REPO}/ .
RUN chmod +x ./mvnw
RUN --mount=type=secret,id=GITHUB_TOKEN,env=GITHUB_TOKEN \
    mkdir -p ~/.m2 && \
    envsubst < ./settings.xml.template > ~/.m2/settings.xml && \
    ./mvnw -f ./pom.xml validate -DskipTests -Dmaven.javadoc.skip=true -Dadditionalparam=-Xdoclint:none -U && \
    ./mvnw -f ./pom.xml clean package -DskipTests -Dmaven.javadoc.skip=true -Dadditionalparam=-Xdoclint:none

### 3. Run stage
FROM amazoncorretto:21-alpine@sha256:6a98c4402708fe8d16e946b4b5bac396379ec5104c1661e2a27b2b45cf9e2d16

RUN addgroup --system user && adduser --ingroup user --system user
USER user:user

ARG EXTRACTED=/workspace/pagopa-ecommerce-event-dispatcher-service/target/

COPY --from=build --chown=user ${EXTRACTED} .

ARG JAR_FILE=pagopa*.jar
ENV APP_NAME=$JAR_FILE

ADD --chown=user https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.25.1/opentelemetry-javaagent.jar .

CMD java -javaagent:opentelemetry-javaagent.jar -jar $APP_NAME