### 1. Cloning stage
FROM alpine/git:latest AS clone
WORKDIR /workspace/pagopa-ecommerce-event-dispatcher-service

ARG ECOMMERCE_EVENT_DISPATCHER_COMMIT_SHA

RUN rm -rf * && \
    git clone https://github.com/pagopa/pagopa-ecommerce-event-dispatcher-service.git /workspace/pagopa-ecommerce-event-dispatcher-service && \
    git checkout ${ECOMMERCE_EVENT_DISPATCHER_COMMIT_SHA} 

### 2. Build stage
FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /workspace/pagopa-ecommerce-event-dispatcher-service/

ARG REPO=/workspace/pagopa-ecommerce-event-dispatcher-service

COPY --from=clone ${REPO}/ .
RUN mvn -f ./pom.xml validate -DskipTests
RUN mvn -f ./pom.xml package -DskipTests

### 3. Run stage
FROM openjdk:17-slim

RUN addgroup --system user && adduser --ingroup user --system user
USER user:user

ARG EXTRACTED=/workspace/pagopa-ecommerce-event-dispatcher-service/target/

COPY --from=build --chown=user ${EXTRACTED} .

ARG JAR_FILE=pagopa*.jar
ENV APP_NAME=$JAR_FILE

ADD --chown=user https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.25.1/opentelemetry-javaagent.jar .

CMD java --enable-preview -javaagent:opentelemetry-javaagent.jar -jar $APP_NAME