ARG JAVA_VERSION=17

### 1. Cloning stage
FROM alpine/git:latest AS clone
WORKDIR /workspace/pagopa-ecommerce-transactions-functions

ARG ECOMMERCE_TRANSACTIONS_FUNCTIONS_COMMIT_SHA

RUN rm -rf * && \
    git clone https://github.com/pagopa/pagopa-ecommerce-transactions-functions.git /workspace/pagopa-ecommerce-transactions-functions && \
    git checkout ${ECOMMERCE_TRANSACTIONS_FUNCTIONS_COMMIT_SHA} 

FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /workspace/pagopa-ecommerce-transactions-functions/

ARG REPO=/workspace/pagopa-ecommerce-transactions-functions

COPY --from=clone ${REPO}/ .

RUN microdnf install git

RUN mvn validate -DskipTests

RUN mkdir -p /home/site/wwwroot
RUN mvn clean package -DskipTests
RUN cd ./target/azure-functions/
RUN cd $(ls -d */|head -n 1) 
RUN cp -a . /home/site/wwwroot

FROM mcr.microsoft.com/azure-functions/java:4-java$JAVA_VERSION-slim

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

EXPOSE 80
COPY --from=build ["/home/site/wwwroot", "/home/site/wwwroot"]