### 1. Cloning stage
FROM alpine/git:latest@sha256:d453f54c83320412aa89c391b076930bd8569bc1012285e8c68ce2d4435826a3 AS clone
WORKDIR /workspace/pagopa-ecommerce-transactions-scheduler-service

ARG ECOMMERCE_TRANSACTIONS_SCHEDULER_COMMIT_SHA

RUN rm -rf * && \
    git clone https://github.com/pagopa/pagopa-ecommerce-transactions-scheduler-service.git /workspace/pagopa-ecommerce-transactions-scheduler-service && \
    git checkout ${ECOMMERCE_TRANSACTIONS_SCHEDULER_COMMIT_SHA} 

### 2. Build stage
FROM maven:3.9.8-eclipse-temurin-21@sha256:de18e4e51396ad9266f76669779ed6d6b49fbb0f45ed6f39169d87378d548d7d AS build
WORKDIR /workspace/pagopa-ecommerce-transactions-scheduler-service/

ARG REPO=/workspace/pagopa-ecommerce-transactions-scheduler-service

RUN apt-get update && apt-get install -y gettext-base

COPY --from=clone ${REPO}/ .
RUN --mount=type=secret,id=GITHUB_TOKEN,env=GITHUB_TOKEN \
    apt-get update && apt-get install -y gettext-base && \
    mkdir -p ~/.m2 && \
    envsubst < ./settings.xml.template > ~/.m2/settings.xml && \
    mvn -f ./pom.xml validate -DskipTests -U && \
    mvn -f ./pom.xml package -DskipTests -U

### 3. Run stage
FROM eclipse-temurin:21-jre-alpine@sha256:8728e354e012e18310faa7f364d00185277dec741f4f6d593af6c61fc0eb15fd

RUN addgroup --system user && adduser --ingroup user --system user
USER user:user

ARG EXTRACTED=/workspace/pagopa-ecommerce-transactions-scheduler-service/target/

COPY --from=build --chown=user ${EXTRACTED} .

ARG JAR_FILE=pagopa*.jar
ENV APP_NAME=$JAR_FILE

ADD --chown=user https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.25.1/opentelemetry-javaagent.jar .

CMD java --enable-preview -javaagent:opentelemetry-javaagent.jar -jar $APP_NAME
