### 1. Cloning stage
FROM alpine/git:latest AS clone
WORKDIR /workspace/pagopa-ecommerce-transactions-scheduler-service

ARG ECOMMERCE_TRANSACTIONS_SCHEDULER_COMMIT_SHA

RUN rm -rf * && \
    git clone https://github.com/pagopa/pagopa-ecommerce-transactions-scheduler-service.git /workspace/pagopa-ecommerce-transactions-scheduler-service && \
    git checkout ${ECOMMERCE_TRANSACTIONS_SCHEDULER_COMMIT_SHA} 

### 2. Build stage
FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /workspace/pagopa-ecommerce-transactions-scheduler-service/

ARG REPO=/workspace/pagopa-ecommerce-transactions-scheduler-service

COPY --from=clone ${REPO}/ .
RUN mvn -f ./pom.xml validate -DskipTests
RUN mvn -f ./pom.xml package -DskipTests

### 3. Run stage
FROM openjdk:17-slim

RUN addgroup --system user && adduser --ingroup user --system user
USER user:user

ARG EXTRACTED=/workspace/pagopa-ecommerce-transactions-scheduler-service/target/

COPY --from=build --chown=user ${EXTRACTED} .

ARG JAR_FILE=*.jar
ENV APP_NAME=$JAR_FILE

CMD java --enable-preview -jar $APP_NAME
