### 1. Cloning stage
FROM alpine/git:latest AS clone
WORKDIR /workspace/pagopa-payment-transactions-gateway
RUN rm -rf * && \
    git clone https://github.com/pagopa/pagopa-payment-transactions-gateway.git /workspace/pagopa-payment-transactions-gateway && \
    git checkout ${PAYMENT_TRANSACTION_GATEWAY_PORT}

### 2. Build stage
FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /workspace/pagopa-payment-transactions-gateway/

ARG REPO=/workspace/pagopa-payment-transactions-gateway

COPY --from=clone ${REPO}/ .
RUN mvn -f ./pom.xml clean package -Pspringboot-postgres

### 3. Run stage
FROM openjdk:17-slim

RUN addgroup --system user && adduser --ingroup user --system user
USER user:user

ARG EXTRACTED=/workspace/pagopa-payment-transactions-gateway/target/

COPY --from=build --chown=user ${EXTRACTED} .

ARG JAR_FILE=*.jar
ENV APP_NAME=$JAR_FILE

CMD java -jar $APP_NAME 