### 1. Cloning stage
FROM alpine/git:latest@sha256:61be893eea3468a255729e31c0a98c2dd9e345dc709e29c291a37d6396ac8e6e AS clone
WORKDIR /workspace/pagopa-ecommerce-transactions-service

ARG ECOMMERCE_TRANSACTIONS_COMMIT_SHA

RUN rm -rf * && \
    git clone https://github.com/pagopa/pagopa-ecommerce-transactions-service.git /workspace/pagopa-ecommerce-transactions-service && \
    git checkout ${ECOMMERCE_TRANSACTIONS_COMMIT_SHA} 

### 2. Build stage
FROM maven:3.8.3-openjdk-17@sha256:8a66581a077762c8752a9f64f73cdd8c59e9c4446eb810417119e0436b075931 AS build
WORKDIR /workspace/pagopa-ecommerce-transactions-service/

ARG REPO=/workspace/pagopa-ecommerce-transactions-service

COPY --from=clone ${REPO}/ .
RUN mvn -f ./pom.xml validate -DskipTests
RUN mvn -f ./pom.xml package -DskipTests

### 3. Run stage
FROM openjdk:17-slim@sha256:aaa3b3cb27e3e520b8f116863d0580c438ed55ecfa0bc126b41f68c3f62f9774

RUN addgroup --system user && adduser --ingroup user --system user
USER user:user

ARG EXTRACTED=/workspace/pagopa-ecommerce-transactions-service/target/

COPY --from=build --chown=user ${EXTRACTED} .

ARG JAR_FILE=pagopa*.jar
ENV APP_NAME=$JAR_FILE
ADD --chown=user https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.25.1/opentelemetry-javaagent.jar .

CMD java --enable-preview -javaagent:opentelemetry-javaagent.jar -jar $APP_NAME
