http:
  routers:
    notifications-router:
      service: "pagopa-notifications-service"
      rule: "PathPrefix(`/notifications-service`)"
      middlewares:
        - notifications-headers
        - notifications-prefix

    nodo-mock-router:
      service: "nodo-mock"
      rule: "PathPrefix(`/nodo`) || PathPrefix(`/webservices`)"
      middlewares:
        - nodo-prefix

    payment-methods-router:
      service: "pagopa-ecommerce-payment-methods-service"
      rule: "PathPrefix(`/payment-methods-service`)"
      middlewares:
        - payment-methods-headers
        - payment-methods-prefix

    payment-methods-handler-router:
      service: "pagopa-ecommerce-payment-methods-handler"
      rule: "PathPrefix(`/payment-methods-handler`)"
      middlewares:
        - payment-methods-handler-headers
        - payment-methods-handler-prefix

  middlewares:

    notifications-headers:
      headers:
        customRequestHeaders:
          X-Client-ID: "CLIENT_ECOMMERCE"
          x-api-key: "PRIMARY-KEY"
    notifications-prefix:
      stripPrefix:
        prefixes:
          - "/notifications-service"

    nodo-prefix:
      stripPrefix:
        prefixes:
          - "/nodo"
    
    payment-methods-prefix:
      stripPrefix:
        prefixes:
          - "/payment-methods-service"
    payment-methods-headers:
      headers:
        customRequestHeaders:
          X-Client-ID: "CHECKOUT"
          x-api-key: "PRIMARY-KEY"

    payment-methods-handler-prefix:
      stripPrefix:
        prefixes:
          - "/payment-methods-handler-service"
    payment-methods-handler-headers:
      headers:
        customRequestHeaders:
          X-Client-ID: "CHECKOUT"
          x-api-key: "PRIMARY-KEY"

  services:
    pagopa-notifications-service:
      loadBalancer:
        servers:
          - url: "http://pagopa-notifications-service:3000"

    nodo-mock:
      loadBalancer:
        servers:
          - url: "http://pagopa-node-mock:3002"

    pagopa-ecommerce-payment-methods-service:
          loadBalancer:
            servers:
              - url: "http://pagopa-ecommerce-payment-methods-service:8080"
