FROM node:20.19.2-alpine@sha256:d3507a213936fe4ef54760a186e113db5188472d9efdf491686bd94580a1c1e8

WORKDIR /usr/src/app

RUN yarn global add json-server@0.17.4 --exact

CMD ["json-server", "/config/jwt-issuer-server.json", "--routes", "/config/routes.json", "--middlewares", "/config/middleware.js", "--host", "0.0.0.0"]
