FROM node:20.19.2-alpine

WORKDIR /usr/src/app

RUN yarn global add json-server@0.17.4 --exact

CMD ["json-server", "/config/jwt-issuer-server.json", "--routes", "/config/routes.json", "--middlewares", "/config/middleware.js", "--host", "0.0.0.0"]
