### 1. Cloning stage
FROM alpine/git:latest AS clone
WORKDIR /workspace/pagopa-ecommerce-payment-instruments-service
RUN rm -rf * && \
    git clone https://github.com/pagopa/pagopa-ecommerce-payment-instruments-service.git /workspace/pagopa-ecommerce-payment-instruments-service && \
    git checkout ${ECOMMERCE_PAYMENT_INSTRUMENTS_COMMIT_SHA} 

### 2. Build stage
FROM maven:3.8.3-openjdk-17 AS build
WORKDIR /workspace/pagopa-ecommerce-payment-instruments-service/

ARG REPO=/workspace/pagopa-ecommerce-payment-instruments-service

COPY --from=clone ${REPO}/ .
RUN mvn -f ./pom.xml clean package

### 3. Run stage
FROM openjdk:17-slim

RUN addgroup --system user && adduser --ingroup user --system user
USER user:user

ARG EXTRACTED=/workspace/pagopa-ecommerce-payment-instruments-service/target/

COPY --from=build --chown=user ${EXTRACTED} .

ARG JAR_FILE=*.jar
ENV APP_NAME=$JAR_FILE

CMD java -jar $APP_NAME