### 1. Cloning stage
FROM alpine/git:latest AS clone
WORKDIR /workspace/pagopa-ecommerce-payment-requests-service

ARG ECOMMERCE_PAYMENT_REQUESTS_COMMIT_SHA

RUN rm -rf * && \
    git clone https://github.com/pagopa/pagopa-ecommerce-payment-requests-service.git /workspace/pagopa-ecommerce-payment-requests-service && \
    git checkout ${ECOMMERCE_PAYMENT_REQUESTS_COMMIT_SHA} 

### 2. Build stage
FROM maven:3.9.9-eclipse-temurin-21 AS build
ARG CACHE_BUST=2025-06-24-java21
WORKDIR /workspace/pagopa-ecommerce-payment-requests-service/

ARG REPO=/workspace/pagopa-ecommerce-payment-requests-service

COPY --from=clone ${REPO}/ .
RUN mvn -f ./pom.xml clean package -DskipTests

### 3. Run stage
FROM eclipse-temurin:21-jre-alpine

RUN addgroup --system user && adduser --ingroup user --system user
USER user:user

ARG EXTRACTED=/workspace/pagopa-ecommerce-payment-requests-service/target/

COPY --from=build --chown=user ${EXTRACTED} .

ARG JAR_FILE=pagopa*.jar
ENV APP_NAME=$JAR_FILE

ADD --chown=user https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.25.1/opentelemetry-javaagent.jar .

CMD java -javaagent:opentelemetry-javaagent.jar -jar $APP_NAME