### 1. Cloning stage
FROM alpine/git:latest AS clone
WORKDIR /workspace/pagopa-ecommerce-payment-methods-service

ARG ECOMMERCE_PAYMENT_METHODS_COMMIT_SHA

RUN rm -rf * && \
    git clone https://github.com/pagopa/pagopa-ecommerce-payment-methods-service.git /workspace/pagopa-ecommerce-payment-methods-service && \
    git checkout CHK-4222-update-java-21
    #git checkout ${ECOMMERCE_PAYMENT_METHODS_COMMIT_SHA}

### 2. Build stage
FROM amazoncorretto:21-alpine@sha256:6a98c4402708fe8d16e946b4b5bac396379ec5104c1661e2a27b2b45cf9e2d16 AS build
WORKDIR /workspace/pagopa-ecommerce-payment-methods-service/

RUN apk add --no-cache git curl ca-certificates

ARG REPO=/workspace/pagopa-ecommerce-payment-methods-service

COPY --from=clone ${REPO}/ .

RUN chmod +x ./mvnw
RUN ./mvnw -f ./pom.xml validate -DskipTests -Dmaven.javadoc.skip=true -Dadditionalparam=-Xdoclint:none
RUN ./mvnw -f ./pom.xml clean package -DskipTests -Dmaven.javadoc.skip=true -Dadditionalparam=-Xdoclint:none

### 3. Run stage
FROM amazoncorretto:21-alpine@sha256:6a98c4402708fe8d16e946b4b5bac396379ec5104c1661e2a27b2b45cf9e2d16

ARG EXTRACTED=/workspace/pagopa-ecommerce-payment-methods-service/target/

COPY --from=build --chown=user ${EXTRACTED} .

ARG JAR_FILE=pagopa*.jar
ENV APP_NAME=$JAR_FILE

ADD --chown=user https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.25.1/opentelemetry-javaagent.jar .

CMD java -javaagent:opentelemetry-javaagent.jar -jar $APP_NAME
