### 1. Cloning stage
FROM alpine/git:latest@sha256:d453f54c83320412aa89c391b076930bd8569bc1012285e8c68ce2d4435826a3 AS clone
WORKDIR /workspace/pagopa-ecommerce-payment-methods-handler

ARG ECOMMERCE_PAYMENT_METHODS_HANDLER_COMMIT_SHA

RUN rm -rf * && \
    git clone https://github.com/pagopa/pagopa-ecommerce-payment-methods-handler.git /workspace/pagopa-ecommerce-payment-methods-handler && \
    git checkout ${ECOMMERCE_PAYMENT_METHODS_HANDLER_COMMIT_SHA} 

### 2. Commons build stage
FROM amazoncorretto:21-alpine@sha256:6a98c4402708fe8d16e946b4b5bac396379ec5104c1661e2a27b2b45cf9e2d16 AS build
WORKDIR /workspace/app
RUN apk add --no-cache findutils git gettext

COPY --from=clone /workspace/pagopa-ecommerce-payment-methods-handler/ ./
RUN chmod +x ./gradlew
RUN --mount=type=secret,id=GITHUB_TOKEN,env=GITHUB_TOKEN \
    ./gradlew build -x test

### 4. Run stage
FROM amazoncorretto:21-alpine@sha256:6a98c4402708fe8d16e946b4b5bac396379ec5104c1661e2a27b2b45cf9e2d16

ARG QUARKUS_APP_FOLDER=/workspace/app/build/quarkus-app
WORKDIR /workspace/run
RUN addgroup --system user && adduser --ingroup user --system user
USER user:user

COPY --from=build --chown=user ${QUARKUS_APP_FOLDER}/ .
ADD --chown=user https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v2.1.0/opentelemetry-javaagent.jar .

ENTRYPOINT ["java"]
CMD ["-javaagent:opentelemetry-javaagent.jar", "-jar", "quarkus-run.jar"]