FROM mcr.microsoft.com/azure-cli:2.47.0

WORKDIR /usr/queues/script

COPY ./azurite-init/create-queues.sh ./create-queues.sh

COPY ../**/*.env ./env-files/

RUN ["chmod" ,"+x" ,"create-queues.sh"]

CMD ["sh","create-queues.sh"]
